---
language: ruby
rvm: 2
cache:
  bundler: true
  directories:
    - bower_components
    - node_modules
sudo: false

before_install:
  - nvm install
  - 'echo ''gem: --no-document'' > ~/.gemrc'

before_script:
  - npm install
