---
title: Make New Jekyll Site Demo
description: Demo site for Make New's Jekyll site skeleton.
name: makenew-jekyll-site
locale: en_US
image: ~
image_asset: ~
color: ~
keywords:
  - jekyll

twitter:
  site: ~
  creator: ~
  card: ~
