---
title: Jekyll Site Skeleton
description: Jekyll site skeleton.
name: makenew-jekyll-site
locale: en_US
image: ~
image_asset: ~
color: ~
keywords:
  - jekyll

twitter:
  site: ~
  creator: ~
  card: ~
